On OTC add GNUTLS_CPUID_OVERRIDE to /etc/environment (#40)
Required because of this issue:

dragon@testbed-manager:~$ git clone https://github.com/osism/cfg-generics
Cloning into 'cfg-generics'...
error: git-remote-https died of signal 4

https://askubuntu.com/questions/1420966/method-https-has-died-unexpectedly-sub-process-https-received-signal-4-after

Signed-off-by: Christian Berendt <berendt@osism.tech>